// Decompiled with JetBrains decompiler
// Type: ObjectLayer
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 6999FFE9-E355-44B6-B5D9-B5C530D5F1A8
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\OxygenNotIncluded\OxygenNotIncluded_Data\Managed\Assembly-CSharp.dll

#nullable disable
public enum ObjectLayer
{
  Minion,
  Building,
  Backwall,
  Pickupables,
  Canvases,
  Plants,
  FillPlacer,
  DigPlacer,
  MopPlacer,
  FoundationTile,
  PlasticTile,
  ReplacementTile,
  GasConduit,
  GasConduitTile,
  ReplacementGasConduit,
  GasConduitConnection,
  LiquidConduit,
  LiquidConduitTile,
  ReplacementLiquidConduit,
  LiquidConduitConnection,
  SolidConduit,
  SolidConduitTile,
  ReplacementSolidConduit,
  SolidConduitConnection,
  LadderTile,
  ReplacementLadder,
  Wire,
  WireTile,
  ReplacementWire,
  WireConnectors,
  LogicGate,
  LogicWire,
  LogicWireTile,
  ReplacementLogicWire,
  TravelTube,
  TravelTubeTile,
  ReplacementTravelTube,
  TravelTubeConnection,
  AttachableBuilding,
  Gantry,
  Mover,
  Rover,
  Critter,
  ReplacementBackwall,
  MovePlacer,
  NumLayers,
}
